import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system";
import { Platform, Linking } from "react-native";

/**
 * Generates a caption for the screenshot share
 */
export function generateShareCaption(
  personalityLabel: string,
  personalityEmoji: string
): string {
  return `${personalityEmoji} ${personalityLabel} reply generated by @ghostreply 🤖✨\n\nGet AI-powered replies for every conversation.\n\n#GhostReply #AIReplies #TikTok #Dating`;
}

/**
 * Shares screenshot to social platforms
 * Supports: TikTok, Instagram, generic Share
 */
export async function shareScreenshotToSocial(
  imageUri: string,
  platform: "tiktok" | "instagram" | "generic",
  caption: string
): Promise<void> {
  try {
    if (Platform.OS === "web") {
      // Web: Open share dialog or download
      await Sharing.shareAsync(imageUri, {
        mimeType: "image/png",
        dialogTitle: "Share to Social Media",
      });
      return;
    }

    // Mobile: Depending on platform
    if (platform === "tiktok") {
      return shareToTikTok(imageUri, caption);
    } else if (platform === "instagram") {
      return shareToInstagram(imageUri, caption);
    } else {
      // Generic share
      return genericShare(imageUri, caption);
    }
  } catch (error) {
    console.error("Share error:", error);
    throw new Error("Failed to share screenshot");
  }
}

/**
 * Share to TikTok via deep link
 * TikTok doesn't have a direct share API, so we copy to clipboard and open TikTok
 */
async function shareToTikTok(imageUri: string, caption: string): Promise<void> {
  try {
    const tiktokUrl = "tiktok://";
    const canOpen = await Linking.canOpenURL(tiktokUrl);

    if (canOpen) {
      // Copy image to clipboard (TikTok can paste from clipboard)
      // For better UX, use the generic share for now
      await genericShare(imageUri, caption);
    } else {
      // Fallback to generic share
      await genericShare(imageUri, caption);
    }
  } catch (error) {
    console.error("TikTok share error:", error);
    throw error;
  }
}

/**
 * Share to Instagram via deep link
 * Opens Instagram with the image file
 */
async function shareToInstagram(imageUri: string, caption: string): Promise<void> {
  try {
    const instagramUrl = "instagram://";
    const canOpen = await Linking.canOpenURL(instagramUrl);

    if (canOpen) {
      // Instagram deep link for sharing
      // Note: Instagram doesn't have a direct share API for images from third-party apps
      // Best practice is to use the system share sheet
      await genericShare(imageUri, caption);
    } else {
      await genericShare(imageUri, caption);
    }
  } catch (error) {
    console.error("Instagram share error:", error);
    throw error;
  }
}

/**
 * Generic system share (shows platform options)
 */
async function genericShare(imageUri: string, caption: string): Promise<void> {
  try {
    // Share the file directly - Sharing will handle validation
    await Sharing.shareAsync(imageUri, {
      mimeType: "image/png",
      dialogTitle: "Share GhostReply Screenshot",
      UTI: "com.apple.app-bundle-identifier",
    });
  } catch (error) {
    console.error("Generic share error:", error);
    throw error;
  }
}

/**
 * Opens user's device browser to download link
 * (for when sharing to web or as a fallback)
 */
export async function openAppDownload(): Promise<void> {
  const ios = "https://apps.apple.com/app/ghostreply/id1234567890";
  const android =
    "https://play.google.com/store/apps/details?id=com.ghostreply";

  try {
    const canOpenIOS = await Linking.canOpenURL(ios);
    const canOpenAndroid = await Linking.canOpenURL(android);

    if (Platform.OS === "ios" && canOpenIOS) {
      await Linking.openURL(ios);
    } else if (Platform.OS === "android" && canOpenAndroid) {
      await Linking.openURL(android);
    } else {
      // Fallback to web
      await Linking.openURL("https://ghostreply.app");
    }
  } catch (error) {
    console.error("Failed to open download link:", error);
  }
}

/**
 * Generates a shareable link with referral code for viral growth
 */
export function generateReferralLink(deviceId: string, platform: string): string {
  const baseUrl = "https://ghostreply.app";
  const params = new URLSearchParams({
    ref: deviceId,
    utm_source: platform,
    utm_medium: "social",
    utm_campaign: "screenshot_share",
  });

  return `${baseUrl}/download?${params.toString()}`;
}
